shipwrecks.xls:
	wget -O shipwrecks.xls https://web.archive.org/web/20070706162608/http://www.vocshipwrecks.nl/downloads/Dutch%20VOC%20Shipwrecks.xls

voyages.csv:
	wget -O voyages.csv http://resources.huygens.knaw.nl/das/voyages_with_opvarenden.csv

crew.csv:
	vocopvarenden > crew.csv
